{{- if .Values.route.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "n8n.fullname" . }}-anyuid-scc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
rules:
- apiGroups: ["security.openshift.io"]
  resourceNames: ["anyuid"]
  resources: ["securitycontextconstraints"]
  verbs: ["use"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "n8n.fullname" . }}-anyuid-scc-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "n8n.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "n8n.fullname" . }}-anyuid-scc
  apiGroup: rbac.authorization.k8s.io
{{- end }}
